In [162]:
import pandas as pd

In [163]:
diabetes_data = pd.read_csv('data/diabetes.csv')

In [164]:
diabetes_data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [165]:
diabetes_data.count()[0]

768

### data augmentation

In [166]:
diabetes_data.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [167]:
#converting Outcome from integer to category
diabetes_data['Outcome'] = pd.Categorical(diabetes_data.Outcome)

In [168]:
diabetes_data.Outcome

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: category
Categories (2, int64): [0, 1]

### Train-Test Split

In [169]:
import math
total_data = diabetes_data.count()[0]
total_training_data = math.floor(total_data*0.7)
total_testing_data = total_data - total_training_data

print('total_data', total_data)
print('total_training_data', total_training_data, total_training_data/total_data)
print('total_testing_data', total_testing_data, total_testing_data/total_data)

total_data 768
total_training_data 537 0.69921875
total_testing_data 231 0.30078125


In [170]:
x_train = diabetes_data[:total_training_data]
x_test = diabetes_data[total_testing_data:]

In [171]:
x_train.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age Outcome  
0                     0.627   50       1  
1                     0.351   31       0  
2                     0.672   32       1  
3                     0.167   21       0  
4                     2.288   33       1

In [172]:
x_test.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
231            6      134             80             37      370  46.2   
232            1       79             80             25       37  25.4   
233            4      122             68              0        0  35.0   
234            3       74             68             28       45  29.7   
235            4      171             72              0        0  43.6   

     DiabetesPedigreeFunction  Age Outcome  
231                     0.238   46       1  
232                     0.583   22       0  
233                     0.394   29       0  
234                     0.293   23       0  
235                     0.479   26       1

In [173]:
y_train = x_train['Outcome']

In [174]:
x_train.drop(columns=['Outcome'], inplace=True)

/var/folders/qs/m16l4x091ybgtw_gh1_vj14r0000gn/T/ipykernel_96950/2900314343.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train.drop(columns=['Outcome'], inplace=True)


In [175]:
x_train

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
532            1       86             66             52       65  41.3   
533            6       91              0              0        0  29.8   
534            1       77             56             30       56  33.3   
535            4      132              0              0        0  32.9   
536            0      105             90              0        0  29.6   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
532                     0.917   29  
533                     0.501   31  
534                     1.251   24  
535                     0.302   23  
536                     0.197   46  

[537 rows x 8 columns]

In [176]:
y_test = x_test['Outcome']
x_test.drop(columns=['Outcome'], inplace=True)

/var/folders/qs/m16l4x091ybgtw_gh1_vj14r0000gn/T/ipykernel_96950/1916130794.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test.drop(columns=['Outcome'], inplace=True)


### Simple linear regreesion

In [177]:
from sklearn import linear_model

In [178]:
#loading the model
linear_regression = linear_model.LinearRegression()

In [179]:
#fitting the model
linear_regression.fit(x_train, y_train)

LinearRegression()

In [180]:
y_pred = linear_regression.predict(x_test)

In [181]:
import numpy as np

In [182]:
y_pred = np.int0(np.abs(np.round(y_pred)))

In [183]:
np.array(y_test)

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,

In [184]:
pred

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,

In [185]:
linear_regression.coef_

array([ 2.22119288e-02,  5.35424490e-03, -2.01407833e-03,  5.57572778e-05,
       -1.74283797e-04,  1.38714128e-02,  1.44911747e-01,  7.93531239e-04])

In [186]:
from sklearn.metrics import mean_squared_error, confusion_matrix, accuracy_score

In [187]:
mean_squared_error(y_test, y_pred)

0.21042830540037244

In [188]:
confusion_matrix(y_test, y_pred)

array([[324,  33],
       [ 80, 100]])

In [189]:
accuracy_score(y_pred, y_test)

0.7895716945996276

### Naive Bayes

In [190]:
from sklearn.naive_bayes import GaussianNB

In [191]:
naive_bayes = GaussianNB()

In [192]:
naive_bayes.fit(x_train, y_train)

GaussianNB()

In [193]:
y_pred_nb = naive_bayes.predict(x_test)

In [194]:
y_pred

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,

In [195]:
mean_squared_error(y_test, y_pred_nb)

0.2271880819366853

In [196]:
confusion_matrix(y_test, y_pred_nb)

array([[304,  53],
       [ 69, 111]])

In [197]:
accuracy_score(y_pred_nb, y_test)

0.7728119180633147

### Decision Tree

In [198]:
from sklearn import neural_network

In [199]:
nn = neural_network.MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)

In [200]:
nn.fit(x_train, y_train)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), random_state=1,
              solver='lbfgs')

In [201]:
y_pred_nn = nn.predict(x_test)

In [202]:
print('accuracy_score', accuracy_score(y_test, y_pred_nn))
print('mean_squared_error', mean_squared_error(y_test, y_pred_nn))
print('confusion_matrix', confusion_matrix(y_test, y_pred_nn))

accuracy_score 0.6834264432029795
mean_squared_error 0.3165735567970205
confusion_matrix [[319  38]
 [132  48]]


In [203]:
from sklearn.svm import SVC

In [204]:
svm = SVC()

In [205]:
svm.fit(x_train, y_train)

SVC()

In [206]:
y_pred_svm = svm.predict(x_test)

In [207]:
print('accuracy_score', accuracy_score(y_test, y_pred_svm))
print('mean_squared_error', mean_squared_error(y_test, y_pred_svm))
print('confusion_matrix', confusion_matrix(y_test, y_pred_svm))

accuracy_score 0.776536312849162
mean_squared_error 0.22346368715083798
confusion_matrix [[322  35]
 [ 85  95]]


### All together

In [208]:
print('accuracy_score lr', accuracy_score(y_test, y_pred))
print('accuracy_score nb', accuracy_score(y_test, y_pred_nb))
print('accuracy_score nn', accuracy_score(y_test, y_pred_nn))
print('accuracy_score svm', accuracy_score(y_test, y_pred_svm))


accuracy_score lr 0.7895716945996276
accuracy_score nb 0.7728119180633147
accuracy_score nn 0.6834264432029795
accuracy_score svm 0.776536312849162


### simple average ensemble

In [209]:
average_prediction = (y_pred+y_pred_nb+y_pred_nn)//3
average_prediction

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [210]:
print('accuracy_score', accuracy_score(y_test, average_prediction))
print('mean_squared_error', mean_squared_error(y_test, average_prediction))
print('confusion_matrix', confusion_matrix(y_test, average_prediction))

accuracy_score 0.7150837988826816
mean_squared_error 0.2849162011173184
confusion_matrix [[348   9]
 [144  36]]


### other ensembles
- Voting
- Bagging
- Boosting

In [211]:
from sklearn.ensemble import VotingClassifier, AdaBoostClassifier

In [212]:
voting = VotingClassifier([
    ('nb', naive_bayes),
    ('nn', nn),
    ('svm', svm),
], voting='soft')

In [213]:
voting.fit(x_train, y_train)

VotingClassifier(estimators=[('nb', GaussianNB()),
                             ('nn',
                              MLPClassifier(alpha=1e-05,
                                            hidden_layer_sizes=(5, 2),
                                            random_state=1, solver='lbfgs')),
                             ('svm', SVC())],
                 voting='soft')

In [214]:
voting.predict([y_test])

/Users/ms/miniforge3/envs/tensorflow-metal/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


ValueError: X has 537 features, but GaussianNB is expecting 8 features as input.

In [215]:
x_test

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
231            6      134             80             37      370  46.2   
232            1       79             80             25       37  25.4   
233            4      122             68              0        0  35.0   
234            3       74             68             28       45  29.7   
235            4      171             72              0        0  43.6   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
231                     0.238   46  
232                     0.583   22  
233                     0.394   29  
234                     0.293   23  
235                     0.479   26  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[537 rows x 8 columns]